import { motion } from 'framer-motion';
import { ContentContainer } from '../layout/ContentContainer';
import { BrainCircuit, CalendarClock, TrendingUp, BarChart3, Target, Layers, Globe, Lock } from 'lucide-react';

const features = [
  {
    icon: BrainCircuit,
    title: "AI Ad Strategy Generation",
    description: "Deep neural networks analyze winning creative combinations across your specific niche.",
    large: true,
  },
  {
    icon: CalendarClock,
    title: "Auto Campaign Scheduling",
    description: "Deploy campaigns during peak velocity windows identified by machine performance data.",
    large: false,
  },
  {
    icon: TrendingUp,
    title: "Budget Optimization",
    description: "Dynamic redistribution of spend to highest ROI ad sets in real-time, 24/7.",
    large: false,
  },
  {
    icon: BarChart3,
    title: "Real-time Analytics",
    description: "Live telemetry streams directly from Meta tracking your unified command center.",
    large: false,
  },
  {
    icon: Target,
    title: "Precision Targeting",
    description: "Laser-focused audience segmentation using behavioral and interest data.",
    large: false,
  },
  {
    icon: Layers,
    title: "Multi-Platform Deploy",
    description: "One click deployment across Facebook, Instagram, Messenger and WhatsApp.",
    large: false,
  },
  {
    icon: Globe,
    title: "Global Reach",
    description: "Target any geography with localized ad copy generated by AI.",
    large: false,
  },
  {
    icon: Lock,
    title: "Enterprise Security",
    description: "Bank-grade encryption keeps your ad account and data completely secure.",
    large: false,
  },
];

export const FeaturesSection = () => {
  return (
    <section id="features" className="py-24 relative overflow-hidden">
      <div className="absolute inset-0 bg-[#060606]" />
      <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-white/5 to-transparent" />

      <ContentContainer className="relative z-10">

        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-80px' }}
          transition={{ duration: 0.5 }}
          className="mb-16 text-center"
        >
          <span className="text-[10px] font-black tracking-widest uppercase text-[#DC2626] mb-3 block">Platform Features</span>
          <h2 className="text-2xl md:text-3xl font-black uppercase tracking-wider text-white mb-4">
            Everything You Need To Dominate
          </h2>
          <p className="text-sm text-gray-500 max-w-lg mx-auto leading-relaxed">
            A complete arsenal of AI-powered tools built specifically for Meta advertising professionals.
          </p>
        </motion.div>

        {/* Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {features.map((feature, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: '-40px' }}
              transition={{ duration: 0.4, delay: (idx % 4) * 0.08 }}
              className="group relative bg-[#101010] border border-white/[0.05] rounded-2xl p-6 hover:border-[#DC2626]/25 transition-all duration-300 overflow-hidden cursor-default"
            >
              {/* Hover glow */}
              <div className="absolute -bottom-8 -right-8 w-28 h-28 bg-[#DC2626]/8 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-500" />

              <div className="w-10 h-10 rounded-xl bg-[#DC2626]/10 border border-[#DC2626]/15 flex items-center justify-center mb-5 group-hover:bg-[#DC2626]/20 transition-colors">
                <feature.icon size={18} className="text-[#DC2626]" />
              </div>
              <h3 className="text-xs font-black text-white uppercase tracking-wide mb-2.5 leading-snug">
                {feature.title}
              </h3>
              <p className="text-[11px] text-gray-500 leading-relaxed font-medium">
                {feature.description}
              </p>
            </motion.div>
          ))}
        </div>
      </ContentContainer>
    </section>
  );
};

